--JOINS
CREATE TABLE T1( C1 CHAR(2), C2 CHAR (2));
CREATE TABLE T2( C1 CHAR(2), C2 CHAR (2));
COMMIT;

INSERT INTO T1 VALUES('A', 'X1');
INSERT INTO T1 VALUES('B', 'X2');

INSERT INTO T2 VALUES ('A', 'Y1');
INSERT INTO T2 VALUES ('C', 'Y2');

SELECT * FROM T1;
SELECT * FROM T2;

--INNER JOIN
SELECT * FROM T1 
INNER JOIN T2 
ON T1.C1= T2.C1;

--LEFT JOIN
SELECT *FROM T1
LEFT JOIN T2
ON T1.C1= T2.C1;

--RIGHT JOIN
SELECT * FROM T1
RIGHT JOIN T2
ON T1.C1= T2.C1;

--FULL OUTER JOIN check for other types
SELECT * FROM T1
FULL OUTER JOIN T2
ON T1.C1= T2.C1;




